version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: techgiterview_dev
      POSTGRES_USER: techgiterview_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "9101:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techgiterview_user -d techgiterview_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "9102:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Chroma Vector Database
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "9103:8000"
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Server
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "9104:8000"
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://techgiterview_user:dev_password@postgres:5432/techgiterview_dev
      - REDIS_URL=redis://redis:6379
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - postgres
      - redis
      - chroma
    volumes:
      - ./src/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Vite App
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "9105:3000"
    environment:
      - VITE_API_URL=http://localhost:9104
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
  chroma_data: