# Docker Compose Override for Development Environment
# 개발 환경 전용 설정

version: '3.8'

services:
  backend:
    environment:
      - ENV=development
      - DEBUG=true
    command: ["/app/.venv/bin/python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
    
  frontend:
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8002
    volumes:
      - ./src/frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3001