version: '3.8'

# Global timeout configurations for build and startup
x-timeout-config: &timeout-config
  COMPOSE_HTTP_TIMEOUT: 300
  DOCKER_CLIENT_TIMEOUT: 300

services:
  # Redis Cache (for future caching needs)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Backend API Server - Development Configuration
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
      target: development  # Use development stage
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "9104:8002"
    environment:
      - ENV=development
      - DEBUG=true
      - DATABASE_PATH=/app/techgiterview_dev.db
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
      - COMPOSE_HTTP_TIMEOUT=300
    depends_on:
      redis:
        condition: service_healthy
    # Simplified volume mounting strategy for development
    volumes:
      # Only mount essential source code for hot-reload
      - ./src/backend/app:/app/app:cached
      - ./src/backend/main.py:/app/main.py:cached
      # Preserve virtual environment in named volume
      - backend_venv:/app/.venv
      # Data directory for SQLite and persistent data
      - backend_data:/app/data
    # Optimized health check with longer startup period
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 45s
      timeout: 30s
      retries: 5
      start_period: 120s  # Allow 2 minutes for startup
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  # Frontend Vite App
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "9105:3001"
    environment:
      - VITE_API_URL=http://localhost:9104
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./src/frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3001
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  backend_data:
    driver: local
  backend_venv:
    driver: local
  frontend_node_modules:
    driver: local