version: '3.8'

services:
  # Redis Cache (Optional - for future caching needs)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Server
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "9104:8002"
    environment:
      - ENV=development
      - DATABASE_PATH=/app/techgiterview_dev.db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./src/backend:/app:cached
      - backend_data:/app/data
    command: ["/app/.venv/bin/python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Vite App
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "9105:3001"
    environment:
      - VITE_API_URL=http://localhost:8002
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3001

volumes:
  redis_data:
  backend_data:
  frontend_node_modules: