# Docker Compose Production Configuration
# Optimized for production deployment

version: '3.8'

services:
  redis:
    restart: always
    # Production Redis configuration
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      target: production  # Use production stage
    restart: always
    environment:
      - ENV=production
      - DEBUG=false
      - DATABASE_PATH=/app/techgiterview_prod.db
      - REDIS_URL=redis://redis:6379
      - ALLOWED_ORIGINS=https://tgv.oursophy.com,http://tgv.oursophy.com,https://techgiterview.com,https://www.techgiterview.com
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    volumes:
      # Only data volumes in production, no source code mounts
      - backend_data_prod:/app/data
      # No .venv volume - it's embedded in the image
    ports:
      - "9104:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    restart: always
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: https://tgv.oursophy.com/api
    environment:
      - NODE_ENV=production
    ports:
      - "9105:80"
    depends_on:
      - backend
    # No volumes in production - static files are embedded

volumes:
  redis_data:
  backend_data_prod: